namespace test_lab_inventory.Models
{
    /// <summary>
    /// Captures a recommendation generated by our AI inspired heuristic layer.
    /// Keeping this model focused allows us to change the way we produce
    /// insights later without touching the UI code.
    /// </summary>
    public class InventoryInsight
    {
        public string Title { get; set; }

        public string Message { get; set; }

        public InsightSeverity Severity { get; set; }
    }

    public enum InsightSeverity
    {
        Informational,
        Warning,
        Critical
    }
}
